[config]
schemaVersion = "0.0.1"

[package]
namespace = "bo0tzz"
name = "VoidChests"
versionNumber = "0.0.1"
description = "Resource chests delete excess items"
websiteUrl = "https://github.com/bo0tzz/voidchests"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Stacklands = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["stacklands"]
categories = []